# Generated by Django 5.1.1 on 2024-10-11 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioWeb', '0002_departamento_estadodelproducto_producto_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado_producto',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estadoUsuario',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='nombre predeterminado', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(default='00000000', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(default='nombre predeterminado', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='nombre predeterminado', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productos', models.ManyToManyField(blank=True, to='sitioWeb.producto')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sitioWeb.usuario')),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
                'db_table': 'Carritos',
            },
        ),
    ]
