# Generated by Django 5.1.1 on 2024-10-11 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitioWeb', '0005_remove_carritoproducto_carrito_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='subCategoria',
        ),
    ]
