# Generated by Django 5.1.1 on 2024-10-11 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioWeb', '0008_categoria_subcategoria_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='sitioWeb.categoria'),
            preserve_default=False,
        ),
    ]
