# Generated by Django 5.1.1 on 2024-10-11 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitioWeb', '0009_alter_subcategoria_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoria',
            new_name='subcategoria',
        ),
    ]
